### ISSUE TITLE
No indicators for idle FluxMonitor

### ISSUE THREAD

**Issue by ebarakos** [smartcontractkit/external-initiator#133]
If oracle is not eligible to submit, FM is not started. We should probably log the reason for the non-eligibility, so we can know if it is expected behavior or something has gone wrong.

**Comment by ebarakos** [comment]
Added just a simple logging on `canSubmitUpdated`, should be sufficient.

**Comment by ebarakos** [comment]
@boxhock if we just receive an event of CanSubmit false, and we want to debug the reason why, what could we do? Any thoughts? Maybe debug it on Substrate itself and do not care EI-wise at all?

**Comment by boxhock** [comment]
Yeah, the EI doesn't have a lot of visibility into why it can't submit, and this is contained entirely on-chain, so I don't think the EI should care about the details around it.
