### ISSUE TITLE
FM is starting even if job is not present in the CL node

### ISSUE THREAD

**Issue by ebarakos** [smartcontractkit/external-initiator#134]
FM starts even the related job is not present in the CL node. What should the behavior be? 

At least we might need an easy way to delete subscriptions(both to CL node + the blockchain), without having to manually do it through db? Maybe something like clear/reset of all subscriptions at least?

**Comment by ebarakos** [comment]
@boxhock any thoguhts on this?

**Comment by boxhock** [comment]
If a job is deleted on the CL node it should automatically get deleted on the EI. Do you have any logs where this isn't the case?

I've talked to Sam about this potentially being an issue, and the conclusion we made was that the node op should just manually call the DELETE endpoint on the EI to get rid of stale jobs, if that ever were to happen.

**Comment by ebarakos** [comment]
Yes, it is deleted, except for the case that EI is down when deleting.

**Comment by ebarakos** [comment]
True. Thanks.
